### ISSUE TITLE
Create a function to set PVs

### ISSUE THREAD

**Issue by canismarko** [spc-group/cdbclerk#1]
## Expected Behavior

In order to update the  EPICS records, we need a function that accepts a group of PV names and the new value needed for each one.

I think this function should have the signature

```python
def set_pvs(record: str, values: Mapping):
    ...
```

So if we have a motor record at ``25idcVME:m`` and we want to update the PV's, we could do:

```python
set_pvs(record="25idcVME:m1", values={'.MRES': 0.001, "VELO": 10.0})
```

## Possible Solution

Create a test that calls this function and checks that the PVs get set properly.

Most likely we'll want to [monkeypatch](https://docs.pytest.org/en/6.2.x/monkeypatch.html) or otherwise mock the call that actually sets the PV.

I suggest using pyepics.caput for now. We can consider other channel access clients later (e.g. aioca).

## Steps to Reproduce (for bugs)

1. Run the tests: ``pytest -v``

**Comment by cjsunatgh** [comment]
Fixed: https://github.com/spc-group/cdbclerk/commit/69c6fecf2739e33cea0521cca733d5eb918b096a
